name: Test template
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: load template
        run: m=""; for i in $(find pandoc -type f); do m=$m" -v ./$i:/usr/local/share/$i"; done && echo "m=$m" >> $GITHUB_ENV
      - name: check loaded file
        run: echo $m
      - name: test preview
        run: docker run --rm -v ./init:/workspace $m ngocptblaplafla/pandoc-texlive-full:nightly --verbose --defaults vnthesis-preview main.md
      - name: test latex
        run: docker run --rm -v ./init:/workspace $m ngocptblaplafla/pandoc-texlive-full:nightly --verbose --defaults vnthesis main.md
